create table if not exists user_sessions (
    user_id text primary key,
    step integer not null default 0,
    answers jsonb not null default '{}'::jsonb,
    recommendations jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists update_user_sessions_updated_at on user_sessions;

create trigger update_user_sessions_updated_at
before update on user_sessions
for each row
execute function update_updated_at_column();

alter table user_sessions enable row level security;

drop policy if exists "Allow anon select user sessions" on user_sessions;
drop policy if exists "Allow anon insert user sessions" on user_sessions;
drop policy if exists "Allow anon update user sessions" on user_sessions;

create policy "Allow anon select user sessions"
on user_sessions
for select
to anon
using (true);

create policy "Allow anon insert user sessions"
on user_sessions
for insert
to anon
with check (true);

create policy "Allow anon update user sessions"
on user_sessions
for update
to anon
using (true)
with check (true);

create table if not exists menu_feedback (
    id bigint generated by default as identity primary key,
    user_id text not null,
    menu_name text not null,
    action text not null check (action in ('dislike', 'choose', 'similar')),
    answers jsonb not null default '{}'::jsonb,
    answer_signature text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_menu_feedback_signature_menu
on menu_feedback (answer_signature, menu_name);

create index if not exists idx_menu_feedback_action_menu
on menu_feedback (action, menu_name);

create unique index if not exists idx_menu_feedback_user_action_signature_menu
on menu_feedback (user_id, menu_name, action, answer_signature);

alter table menu_feedback enable row level security;

drop policy if exists "Allow anon select menu feedback" on menu_feedback;
drop policy if exists "Allow anon insert menu feedback" on menu_feedback;

create policy "Allow anon select menu feedback"
on menu_feedback
for select
to anon
using (true);

create policy "Allow anon insert menu feedback"
on menu_feedback
for insert
to anon
with check (true);

create table if not exists toss_usage_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    event_name text not null check (
        event_name in (
            'app_open',
            'questions_loaded',
            'recommendation_completed',
            'feedback_clicked',
            'share_clicked',
            'restart_clicked'
        )
    ),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_toss_usage_events_user
on toss_usage_events (user_id);

create index if not exists idx_toss_usage_events_event_created_at
on toss_usage_events (event_name, created_at desc);

alter table toss_usage_events enable row level security;

drop policy if exists "Allow anon select toss usage events" on toss_usage_events;
drop policy if exists "Allow anon insert toss usage events" on toss_usage_events;

create policy "Allow anon select toss usage events"
on toss_usage_events
for select
to anon
using (true);

create policy "Allow anon insert toss usage events"
on toss_usage_events
for insert
to anon
with check (true);
