create table if not exists kakao_usage_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    event_name text not null check (
        event_name in (
            'kakao_start',
            'kakao_question_answered',
            'kakao_recommendation_completed',
            'kakao_feedback_clicked',
            'kakao_restart'
        )
    ),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_kakao_usage_events_user
on kakao_usage_events (user_id);

create index if not exists idx_kakao_usage_events_event_created_at
on kakao_usage_events (event_name, created_at desc);

grant select, insert on table kakao_usage_events to anon;
grant select, insert on table kakao_usage_events to service_role;
grant usage, select on sequence kakao_usage_events_id_seq to anon;
grant usage, select on sequence kakao_usage_events_id_seq to service_role;

alter table kakao_usage_events enable row level security;

drop policy if exists "Allow anon select kakao usage events" on kakao_usage_events;
drop policy if exists "Allow anon insert kakao usage events" on kakao_usage_events;

create policy "Allow anon select kakao usage events"
on kakao_usage_events
for select
to anon
using (true);

create policy "Allow anon insert kakao usage events"
on kakao_usage_events
for insert
to anon
with check (true);
