-- Apply this in the production Supabase SQL Editor before Toss QR testing.
-- It persists Toss miniapp usage events that are exposed through /api/toss/metrics.

create table if not exists toss_usage_events (
    id bigint generated by default as identity primary key,
    user_id text not null,
    event_name text not null check (
        event_name in (
            'app_open',
            'questions_loaded',
            'recommendation_completed',
            'feedback_clicked',
            'share_clicked',
            'restart_clicked'
        )
    ),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_toss_usage_events_user
on toss_usage_events (user_id);

create index if not exists idx_toss_usage_events_event_created_at
on toss_usage_events (event_name, created_at desc);

grant select, insert on table toss_usage_events to anon;
grant select, insert on table toss_usage_events to service_role;
grant usage, select on sequence toss_usage_events_id_seq to anon;
grant usage, select on sequence toss_usage_events_id_seq to service_role;

alter table toss_usage_events enable row level security;

drop policy if exists "Allow anon select toss usage events" on toss_usage_events;
drop policy if exists "Allow anon insert toss usage events" on toss_usage_events;

create policy "Allow anon select toss usage events"
on toss_usage_events
for select
to anon
using (true);

create policy "Allow anon insert toss usage events"
on toss_usage_events
for insert
to anon
with check (true);
